#ifndef IDI_APP_ICON
#define IDI_APP_ICON 101
#endif

#ifndef IDI_TRAY_ICON
#define IDI_TRAY_ICON 102
#endif

#ifndef IDD_SETTINGS_DIALOG
#define IDD_SETTINGS_DIALOG 202
#endif

#ifndef IDC_SETTINGS_START_WITH_WINDOWS
#define IDC_SETTINGS_START_WITH_WINDOWS 10003
#endif

#ifndef IDC_SETTINGS_SHOW_STATUS_PILL
#define IDC_SETTINGS_SHOW_STATUS_PILL 10004
#endif

#ifndef IDC_SETTINGS_TOGGLE_HOTKEY
#define IDC_SETTINGS_TOGGLE_HOTKEY 10005
#endif

#ifndef IDC_SETTINGS_CANCEL_HOTKEY
#define IDC_SETTINGS_CANCEL_HOTKEY 10006
#endif

#ifndef IDC_SETTINGS_STATUS_PILL_POSITION
#define IDC_SETTINGS_STATUS_PILL_POSITION 10007
#endif

#ifndef IDC_SETTINGS_STATUS_PILL_POSITION_LABEL
#define IDC_SETTINGS_STATUS_PILL_POSITION_LABEL 10008
#endif

#ifndef IDC_SETTINGS_HOTKEY_HINT
#define IDC_SETTINGS_HOTKEY_HINT 10009
#endif

#ifndef IDC_SETTINGS_TABS
#define IDC_SETTINGS_TABS 10011
#endif

#ifndef IDC_SETTINGS_TRANSCRIPTION_PROVIDER_LABEL
#define IDC_SETTINGS_TRANSCRIPTION_PROVIDER_LABEL 10012
#endif

#ifndef IDC_SETTINGS_TRANSCRIPTION_PROVIDER
#define IDC_SETTINGS_TRANSCRIPTION_PROVIDER 10013
#endif

#ifndef IDC_SETTINGS_LANGUAGE_HINT_LABEL
#define IDC_SETTINGS_LANGUAGE_HINT_LABEL 10014
#endif

#ifndef IDC_SETTINGS_LANGUAGE_HINT
#define IDC_SETTINGS_LANGUAGE_HINT 10015
#endif

#ifndef IDC_SETTINGS_TOGGLE_HOTKEY_LABEL
#define IDC_SETTINGS_TOGGLE_HOTKEY_LABEL 10016
#endif

#ifndef IDC_SETTINGS_CANCEL_HOTKEY_LABEL
#define IDC_SETTINGS_CANCEL_HOTKEY_LABEL 10017
#endif

#ifndef IDC_SETTINGS_SAVE_HINT
#define IDC_SETTINGS_SAVE_HINT 10018
#endif

#ifndef IDC_SETTINGS_OPENAI_MODEL_LABEL
#define IDC_SETTINGS_OPENAI_MODEL_LABEL 10019
#endif

#ifndef IDC_SETTINGS_OPENAI_MODEL
#define IDC_SETTINGS_OPENAI_MODEL 10020
#endif

#ifndef IDC_SETTINGS_OPENAI_TARGET_LABEL
#define IDC_SETTINGS_OPENAI_TARGET_LABEL 10021
#endif

#ifndef IDC_SETTINGS_OPENAI_TARGET
#define IDC_SETTINGS_OPENAI_TARGET 10022
#endif

#ifndef IDC_SETTINGS_OPENAI_API_KEY_LABEL
#define IDC_SETTINGS_OPENAI_API_KEY_LABEL 10023
#endif

#ifndef IDC_SETTINGS_OPENAI_API_KEY
#define IDC_SETTINGS_OPENAI_API_KEY 10024
#endif

#ifndef IDC_SETTINGS_OPENAI_REMOVE_KEY
#define IDC_SETTINGS_OPENAI_REMOVE_KEY 10025
#endif

#ifndef IDC_SETTINGS_OPENAI_API_KEY_HINT
#define IDC_SETTINGS_OPENAI_API_KEY_HINT 10026
#endif

#ifndef IDC_SETTINGS_OPENAI_PROMPT_LABEL
#define IDC_SETTINGS_OPENAI_PROMPT_LABEL 10027
#endif

#ifndef IDC_SETTINGS_OPENAI_PROMPT
#define IDC_SETTINGS_OPENAI_PROMPT 10028
#endif

#ifndef IDC_SETTINGS_MISTRAL_MODEL_LABEL
#define IDC_SETTINGS_MISTRAL_MODEL_LABEL 10029
#endif

#ifndef IDC_SETTINGS_MISTRAL_MODEL
#define IDC_SETTINGS_MISTRAL_MODEL 10030
#endif

#ifndef IDC_SETTINGS_MISTRAL_TARGET_LABEL
#define IDC_SETTINGS_MISTRAL_TARGET_LABEL 10031
#endif

#ifndef IDC_SETTINGS_MISTRAL_TARGET
#define IDC_SETTINGS_MISTRAL_TARGET 10032
#endif

#ifndef IDC_SETTINGS_MISTRAL_API_KEY_LABEL
#define IDC_SETTINGS_MISTRAL_API_KEY_LABEL 10033
#endif

#ifndef IDC_SETTINGS_MISTRAL_API_KEY
#define IDC_SETTINGS_MISTRAL_API_KEY 10034
#endif

#ifndef IDC_SETTINGS_MISTRAL_REMOVE_KEY
#define IDC_SETTINGS_MISTRAL_REMOVE_KEY 10035
#endif

#ifndef IDC_SETTINGS_MISTRAL_API_KEY_HINT
#define IDC_SETTINGS_MISTRAL_API_KEY_HINT 10036
#endif

#ifndef IDC_SETTINGS_MISTRAL_CONTEXT_BIAS_LABEL
#define IDC_SETTINGS_MISTRAL_CONTEXT_BIAS_LABEL 10037
#endif

#ifndef IDC_SETTINGS_MISTRAL_CONTEXT_BIAS
#define IDC_SETTINGS_MISTRAL_CONTEXT_BIAS 10038
#endif

#ifndef IDC_SETTINGS_RESET_DEFAULTS
#define IDC_SETTINGS_RESET_DEFAULTS 10039
#endif

#ifndef IDC_SETTINGS_ARCHIVE_ENABLED
#define IDC_SETTINGS_ARCHIVE_ENABLED 10040
#endif

#ifndef IDC_SETTINGS_ARCHIVE_TRANSCRIPT
#define IDC_SETTINGS_ARCHIVE_TRANSCRIPT 10041
#endif

#ifndef IDC_SETTINGS_ARCHIVE_AUDIO
#define IDC_SETTINGS_ARCHIVE_AUDIO 10042
#endif

#ifndef IDC_SETTINGS_ARCHIVE_FOLDER_LABEL
#define IDC_SETTINGS_ARCHIVE_FOLDER_LABEL 10043
#endif

#ifndef IDC_SETTINGS_ARCHIVE_FOLDER
#define IDC_SETTINGS_ARCHIVE_FOLDER 10044
#endif

#ifndef IDC_SETTINGS_ARCHIVE_BROWSE
#define IDC_SETTINGS_ARCHIVE_BROWSE 10045
#endif

#ifndef IDC_SETTINGS_ARCHIVE_HINT
#define IDC_SETTINGS_ARCHIVE_HINT 10046
#endif

#ifndef IDC_SETTINGS_USE_MEDIA_PLAY_PAUSE_TOGGLE
#define IDC_SETTINGS_USE_MEDIA_PLAY_PAUSE_TOGGLE 10047
#endif
