#ifndef IDI_APP_ICON
#define IDI_APP_ICON 101
#endif

#ifndef IDI_TRAY_ICON
#define IDI_TRAY_ICON 102
#endif

#ifndef IDD_OPENAI_KEY_DIALOG
#define IDD_OPENAI_KEY_DIALOG 201
#endif

#ifndef IDD_SETTINGS_DIALOG
#define IDD_SETTINGS_DIALOG 202
#endif

#ifndef IDC_OPENAI_TARGET_VALUE
#define IDC_OPENAI_TARGET_VALUE 10001
#endif

#ifndef IDC_OPENAI_API_KEY_EDIT
#define IDC_OPENAI_API_KEY_EDIT 10002
#endif

#ifndef IDC_SETTINGS_START_WITH_WINDOWS
#define IDC_SETTINGS_START_WITH_WINDOWS 10003
#endif

#ifndef IDC_SETTINGS_SHOW_STATUS_PILL
#define IDC_SETTINGS_SHOW_STATUS_PILL 10004
#endif

#ifndef IDC_SETTINGS_TOGGLE_HOTKEY
#define IDC_SETTINGS_TOGGLE_HOTKEY 10005
#endif

#ifndef IDC_SETTINGS_CANCEL_HOTKEY
#define IDC_SETTINGS_CANCEL_HOTKEY 10006
#endif

#ifndef IDC_SETTINGS_STATUS_PILL_POSITION
#define IDC_SETTINGS_STATUS_PILL_POSITION 10007
#endif

#ifndef IDC_SETTINGS_STATUS_PILL_POSITION_LABEL
#define IDC_SETTINGS_STATUS_PILL_POSITION_LABEL 10008
#endif

#ifndef IDC_SETTINGS_HOTKEY_HINT
#define IDC_SETTINGS_HOTKEY_HINT 10009
#endif
